<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<dict>
  <key>fileTypes</key>
  <array> 
    <string>snow</string>
   </array>
  <key>name</key>
  <string>snowman</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.snowman</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(show|input|type)</string>
          <key>name</key>
          <string>entity.name.function.snowman</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(string|int|bool|index|value)</string>
          <key>name</key>
          <string>support.type.snowman</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(for|in|while|do|to)</string>
          <key>name</key>
          <string>keyword.snowman</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false)</string>
          <key>name</key>
          <string>constant.language.snowman</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\.)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.function.snowman</string>
          <key>end</key>
          <string>(\(*\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.snowman</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.snowman</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.snowman</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z]*)</string>
          <key>name</key>
          <string>variable.other.snowman</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.snowman</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.snowman</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.snowman</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.snowman</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
